### ISSUE TITLE
source attribute could be undefined

### ISSUE THREAD

**Issue by iegik** [expo/react-native-responsive-image#4]
```
TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
      
      at Function.getClosestHighQualitySource (node_modules/@expo/react-native-responsive-image/ResponsiveImage.js:83:136)
      at ResponsiveImage.render (node_modules/@expo/react-native-responsive-image/ResponsiveImage.js:59:35)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:796:21
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:795:25)
      at ReactCompositeComponentWrapper._renderValidatedComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:822:32)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:362:30)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)

```

**Comment by ide** [comment]
You have to pass in valid image sources, otherwise there is nothing to display.

**Comment by iegik** [comment]
I think, this is a bug. Should be checked for undefined in the code.
